### ISSUE TITLE
npm ERR! Error: failed to fetch from registry: react-timer-mixin

### ISSUE THREAD

**Issue by yansha87** [race604/ZhiHuDaily-React-Native#35]
_When running "npm install" in project root directory, error happen:_

```
npm http GET https://registry.npmjs.org/react-native
npm http GET https://registry.npmjs.org/react-native-drawer
npm http GET https://registry.npmjs.org/react-native-viewpager
npm http GET https://registry.npmjs.org/react-timer-mixin

npm ERR! Error: failed to fetch from registry: react-timer-mixin
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1261:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/demon/Workspace/ZhiHuDaily-React-Native/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.11.0-26-generic
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /home/demon/Workspace/ZhiHuDaily-React-Native
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: react-timer-mixin
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/demon/Workspace/ZhiHuDaily-React-Native/npm-debug.log
npm not ok
```

**Comment by yansha87** [comment]
Update npm resolved this issue for me, it looks like the version of npm 1.1.4 not supported now. [from stackoverflow](http://stackoverflow.com/questions/12913141/message-failed-to-fetch-from-registry-while-trying-to-install-any-module)
