### ISSUE TITLE
不知道为什么会卡顿

### ISSUE THREAD

**Issue by vlike** [race604/ZhiHuDaily-React-Native#41]
首页的文章列表，轻点下去后，都会卡一到两秒才进入阅读界面。研究了很久也没找出原因，有知道的吗？

**Comment by willwee** [comment]
我的第一次下来会报如下的错误，能帮忙看下什么问题吗？感谢。
D:\react\zhihudaily>npm install

D:\react\zhihudaily>react-native start
module.js:339
    throw err;
    ^

Error: Cannot find module 'yeoman-environment'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (D:\react\zhihudaily\node_modules\react-native\local-cli\generate-androi
d.js:5:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

**Comment by wilcosheh** [comment]
确实会卡顿，而且上划获取下一列表的时候很慢，感觉是一条一条给加载出来的，有没有研究如何优化的

**Comment by guoyoujin** [comment]
@wilcosheh @vlike 我也有这种感觉，我居然可以以肉眼看到每一个item一条一条加载进来，这让我感到非常不可思议，还有就是点击的时候反应非常慢，我知道是我们代码写的有问题还是RN在android上就是这个样子
